[package]
name = "xcm-procedural"
edition = "2021"
repository = "https://github.com/paritytech/polkadot.git"
version = "0.9.41"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0.56"
quote = "1.0.26"
syn = "2.0.15"
Inflector = "0.11.4"
